language: python
python:
  - "3.6"
  - "3.7-dev"

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - pytest --cov=app test_app.py --cov-report term-missing
  - mypy --ignore-missing-imports app.py

after_success:
  - codecov -t=$CODECOV_TOKEN
